apiVersion: apps/v1
kind: Deployment
metadata:
  name: networksecurity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: networksecurity
  template:
    metadata:
      labels:
        app: networksecurity
    spec:
      containers:
      - name: networksecurity
        image: us-central1-docker.pkg.dev/network-security-483613/networksecurity/networksecurity:latest
        ports:
        - containerPort: 8000
        env:
        - name: GCS_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: networksecurity-secrets
              key: GCS_BUCKET_NAME
        - name: GCS_DATA_FILE
          valueFrom:
            secretKeyRef:
              name: networksecurity-secrets
              key: GCS_DATA_FILE
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: oauth-secrets
              key: GOOGLE_CLIENT_ID
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth-secrets
              key: GOOGLE_CLIENT_SECRET
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: oauth-secrets
              key: SECRET_KEY
